#!/usr/bin/env bash
# Setting up server to curl port 80  



#remove default enabled 
rm /etc/nginx/sites-enabled/default

#config nginx 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
sudo service nginx restart
